{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  resourceNames:
  - "ipclaim-scheduler"
  verbs:
  - '*'
- apiGroups:
  - ipcontroller.ext
  resources:
  - ipclaims
  - ipnodes
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fullname" . }}
{{- end }}
